#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import yaml

VALID_SIMD = ("NONE", "AVX2", "NEON")
OUTPUT_NAMES = {
    "NONE": "fft_none.inc",
    "AVX2": "fft_avx2.inc",
    "NEON": "fft_neon.inc",
}


def format_float(value: object) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return repr(value)
    raise TypeError(f"Unsupported tolerance value: {value!r}")


def get_tolerance(case: dict, tol_key: str, simd: str, test_name: str, size: int) -> str | None:
    if tol_key not in case:
        raise ValueError(
            f"Test '{test_name}' case for size {size} must define {tol_key}."
        )
    tol_map = case[tol_key]
    if not isinstance(tol_map, dict):
        raise ValueError(
            f"Test '{test_name}' case for size {size} must define {tol_key} as a mapping."
        )

    invalid_keys = sorted(set(tol_map) - set(VALID_SIMD))
    if invalid_keys:
        raise ValueError(
            f"Test '{test_name}' case for size {size} has invalid {tol_key} keys: {invalid_keys}"
        )

    if simd not in tol_map:
        return None
    return format_float(tol_map[simd])


def render_test(test: dict, simd: str) -> str | None:
    name = test.get("name")
    if not isinstance(name, str) or not name:
        raise ValueError("Each test must have a non-empty string 'name'.")

    cases = test.get("cases")
    if not isinstance(cases, list) or not cases:
        raise ValueError(f"Test '{name}' must have a non-empty 'cases' list.")

    rendered_cases: list[str] = []
    for case in cases:
        if not isinstance(case, dict):
            raise ValueError(f"Test '{name}' has a non-mapping case entry.")
        size = case.get("size")
        if not isinstance(size, int) or size <= 0:
            raise ValueError(f"Test '{name}' has invalid size: {size!r}")

        forward_tol = get_tolerance(case, "forward_tol", simd, name, size)
        inverse_tol = get_tolerance(case, "inverse_tol", simd, name, size)

        if (forward_tol is None) != (inverse_tol is None):
            raise ValueError(
                f"Test '{name}' case for size {size} must define both forward and inverse tolerances for SIMD_TYPE::{simd}, or neither."
            )

        if forward_tol is None:
            continue

        rendered_cases.extend(
            [
                "    {",
                f"        auto ans = fft_opt_tester<{size}, SIMD_TYPE::{simd}>();",
                f"        CHECK(ans.first < {forward_tol});",
                f"        CHECK(ans.second < {inverse_tol});",
                "    }",
            ]
        )

    if not rendered_cases:
        return None

    test_name = name if simd == "NONE" else f"{name} [{simd}]"
    lines = [f'TEST_CASE("{test_name}") {{']
    lines.extend(rendered_cases)
    lines.append("}")
    return "\n".join(lines)


def collect_tests(spec_dir: Path) -> list[tuple[Path, list[dict]]]:
    collected: list[tuple[Path, list[dict]]] = []
    for spec_path in sorted(spec_dir.glob("*.yaml")):
        with spec_path.open("r", encoding="utf-8") as handle:
            data = yaml.safe_load(handle) or {}
        if not isinstance(data, dict):
            raise ValueError(f"{spec_path}: top-level YAML must be a mapping.")
        tests = data.get("tests", [])
        if not isinstance(tests, list):
            raise ValueError(f"{spec_path}: tests must be a list.")
        collected.append((spec_path, tests))
    return collected


def render_include(specs: list[tuple[Path, list[dict]]], simd: str) -> str:
    rendered_tests: list[str] = []
    source_names: list[str] = []
    for spec_path, tests in specs:
        source_names.append(spec_path.as_posix())
        for test in tests:
            rendered = render_test(test, simd)
            if rendered is not None:
                rendered_tests.append(rendered)

    lines = [
        "// Generated by tools/generate_fft_doctest.py. Do not edit manually.",
        "// Source specs:",
    ]
    for source_name in source_names:
        lines.append(f"//   {source_name}")
    lines.append("")

    if rendered_tests:
        lines.append("\n\n".join(rendered_tests))
    else:
        lines.append(f"// No tests defined for SIMD_TYPE::{simd}.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--spec-dir", required=True)
    parser.add_argument("--out-dir", required=True)
    args = parser.parse_args()

    spec_dir = Path(args.spec_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    specs = collect_tests(spec_dir)
    for simd in VALID_SIMD:
        (out_dir / OUTPUT_NAMES[simd]).write_text(
            render_include(specs, simd), encoding="utf-8"
        )

    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise
